version: "3.6"
services:
  gitlab:
    image: "dfulop98/babilon-demo:latest"
    container_name: babilon-test
    restart: always
    ports:
      - "23080:80"
      - "23443:443"
      - "23022:22"
    shm_size: "5gb"
    networks:
      - gitlab_network

  runners:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runners
    networks:
      - gitlab_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/runners:/etc/gitlab-runner

networks:
  gitlab_network:
    external: true
