version: "3.6"
services:
  gitlab:
    image: "dfulop98/babilon-demo:latest"
    container_name: babilon-test
    restart: always
    volumes:
      - "gitlab_config:/etc/gitlab"
      - "gitlab_logs:/var/opt/gitlab"
      - "gitlab_data:/var/opt/gitlab"
    ports:
      - "23080:80"
      - "23443:443"
      - "23022:22"
    shm_size: "5gb"
    networks:
      - gitlab_network

  linux_runners:
    image: gitlab/gitlab-runner:latest
    networks:
      - gitlab_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cert/ssl:/etc/gitlab-runner/certs/
      - ./config/linux-runners:/etc/gitlab-runner
    depends_on:
      - gitlab

  dockerizer_runner:
    image: gitlab/gitlab-runner:latest
    networks:
      - gitlab_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cert/ssl:/etc/gitlab-runner/certs/
      - ./config/windows-runners:/etc/gitlab-runner
    depends_on:
      - gitlab

volumes:
  gitlab_config:
  gitlab_data:
  gitlab_logs:

networks:
  gitlab_network:
    external: true
