version: "3.6"
services:
  gitlab:
    image: "dfulop98/babilon-demo:latest"
    container_name: babilon-test
    restart: always
    volumes:
      - "gitlab_config:/etc/gitlab"
      - "gitlab_logs:/var/opt/gitlab"
      - "gitlab_data:/var/opt/gitlab"
    ports:
      - "23080:80"
      - "23443:443"
      - "23022:22"
    shm_size: "5gb"
    networks:
      - gitlab_network

  notification_runner:
    image: gitlab/gitlab-runner:latest
    networks:
      - gitlab_network
    command:
      - /bin/bash
      - -c
      - |
        chmod +x ./register-runner.sh
        ./register-runner.sh
        gitlab-runner run
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cert/ssl:/etc/gitlab-runner/certs/
      - ./runner_registers/notify_runner.sh:/register-runner.sh

  build_runner:
    image: gitlab/gitlab-runner:latest
    networks:
      - gitlab_network
    command:
      - /bin/bash
      - -c
      - |
        chmod +x ./register-runner.sh
        ./register-runner.sh
        gitlab-runner run
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cert/ssl:/etc/gitlab-runner/certs/
      - ./runner_registers/build_runner.sh:/register-runner.sh

  test_runner:
    image: gitlab/gitlab-runner:latest
    networks:
      - gitlab_network
    command:
      - /bin/bash
      - -c
      - |
        chmod +x ./register-runner.sh
        ./register-runner.sh
        gitlab-runner run
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cert/ssl:/etc/gitlab-runner/certs/
      - ./runner_registers/test_runner.sh:/register-runner.sh

  archive_runner:
    image: gitlab/gitlab-runner:latest
    networks:
      - gitlab_network
    command:
      - /bin/bash
      - -c
      - |
        chmod +x ./register-runner.sh
        ./register-runner.sh
        gitlab-runner run
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cert/ssl:/etc/gitlab-runner/certs/
      - ./runner_registers/archive_runner.sh:/register-runner.sh

  dockerizer_runner:
    image: gitlab/gitlab-runner:latest
    networks:
      - gitlab_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cert/ssl:/etc/gitlab-runner/certs/
      - ./runner_registers/dockerizer_runner.sh:/register-runner.sh

volumes:
  gitlab_config:
  gitlab_data:
  gitlab_logs:

networks:
  gitlab_network:
    external: true
