version: "3.6"
services:
  gitlab:
    image: "dfulop98/babilon-demo:latest"
    container_name: babilon-test
    restart: always
    volumes:
      - "gitlab_config:/etc/gitlab"
      - "gitlab_logs:/var/log/gitlab"
      - "gitlab_data:/var/opt/gitlab"
      - "./backups:/var/opt/gitlab/backups"
      - "./config_backups:/etc/gitlab"
      - "./restore.sh:/restore.sh"
    ports:
      - "23080:80"
      - "23443:443"
      - "23022:22"
    shm_size: "5gb"
    networks:
      - gitlab_network

  runners:
    image: gitlab/gitlab-runner:latest
    networks:
      - gitlab_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/runners:/etc/gitlab-runner

volumes:
  gitlab_config:
  gitlab_data:
  gitlab_logs:

networks:
  gitlab_network:
    external: true
