version: "3.6"
services:
  gitlab:
    image: "dfulop98/my_gitlab_server:latest"
    container_name: babilon-gitlab
    restart: always
    entrypoint: /entrypoint.sh
    ports:
      - "23080:80"
      - "23443:443"
      - "23022:22"
    volumes:
      - "gitlab_logs:/var/log/gitlab"
      - "gitlab_data:/var/opt/gitlab"
      - "./entrypoint.sh:/entrypoint.sh"
    shm_size: "5gb"
    networks:
      - gitlab_network

  notification_runner:
    image: gitlab/gitlab-runner:latest
    networks:
      - gitlab_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CI_SERVER_URL=https://192.168.3.240
      - REGISTRATION_TOKEN=glrt-Qe7LvFRgFyPLkSbLtXNy
      - RUNNER_NAME=notification_runner
      - RUNNER_EXECUTOR=docker
      - DOCKER_IMAGE=docker:stable
      - RUNNER_TAGS=notification

  build_runner:
    image: gitlab/gitlab-runner:latest
    networks:
      - gitlab_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CI_SERVER_URL=https://192.168.3.240
      - REGISTRATION_TOKEN=glrt-xPGszsm8V6f_QyecRyUS
      - RUNNER_NAME=build_runner
      - RUNNER_EXECUTOR=docker
      - DOCKER_IMAGE=docker:stable
      - RUNNER_TAGS=build
  test_runner:
    image: gitlab/gitlab-runner:latest
    networks:
      - gitlab_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CI_SERVER_URL=https://192.168.3.240
      - REGISTRATION_TOKEN=glrt-zB6kGaTpHZmiemxTR1j8
      - RUNNER_NAME=test_runner
      - RUNNER_EXECUTOR=docker
      - DOCKER_IMAGE=docker:stable
      - RUNNER_TAGS=test

  archive_runner:
    image: gitlab/gitlab-runner:latest
    networks:
      - gitlab_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CI_SERVER_URL=https://192.168.3.240
      - REGISTRATION_TOKEN=glrt-6kS-74CxppUbzMMUJfky
      - RUNNER_NAME=archive_runner
      - RUNNER_EXECUTOR=docker
      - DOCKER_IMAGE=docker:stable
      - RUNNER_TAGS=archive

  dockerizer_runner:
    image: gitlab/gitlab-runner:latest
    networks:
      - gitlab_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CI_SERVER_URL=https://192.168.3.240
      - REGISTRATION_TOKEN=glrt-Nphj5Ro7aftq1vmAhfse
      - RUNNER_NAME=dockerizer_runner
      - RUNNER_EXECUTOR=docker
      - DOCKER_IMAGE=mcr.microsoft.com/windows/nanoserver:ltsc2019
      - RUNNER_TAGS=dockerizer

volumes:
  gitlab_config:
  gitlab_data:
  gitlab_logs:

networks:
  gitlab_network:
    external: true
