concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "notify_runner"
  url = "https://192.168.3.240:23443"
  id = 37
  token = "glrt-DjqtSaKz6yg6V76ytx8v"
  token_obtained_at = 2023-08-12T21:26:28Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "docker:stable"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0

[[runners]]
  name = "build_runner"
  url = "https://192.168.3.240:23443"
  id = 37
  token = "glrt-xPGszsm8V6f_QyecRyUS"
  token_obtained_at = 2023-08-12T21:26:28Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "docker:stable"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0

[[runners]]
  name = "test_runner"
  url = "https://192.168.3.240:23443"
  id = 37
  token = "glrt-zB6kGaTpHZmiemxTR1j8"
  token_obtained_at = 2023-08-12T21:26:28Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "docker:stable"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  
[[runners]]
  name = "archive_runner"
  url = "https://192.168.3.240:23443"
  id = 37
  token = "glrt-6kS-74CxppUbzMMUJfky"
  token_obtained_at = 2023-08-12T21:26:28Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "docker:stable"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0

  