version: "3.6"

services:
  example_runner:
    image: gitlab/gitlab-runner:latest
    networks:
      - gitlab_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CI_SERVER_URL=https://REPLACE_WITH_IP
      - REGISTRATION_TOKEN=REPLACE_WITH_TOKEN
      - RUNNER_NAME=REPLACE_WITH_NAME
      - RUNNER_EXECUTOR=REPLACE_WITH_EXECUTOR
      - DOCKER_IMAGE=REPLACE_WITH_IMAGE
      - RUNNER_TAGS=REPLACE_WITH_TAGS

## Other runner ......

networks:
  gitlab_network:
    external: true
